name: "Automatic Releases"
author: "marvinpinto"
description: "Automate the GitHub release process with assets, changelogs, pre-releases, and more"
inputs:
  repo_token:
    description: "GitHub secret token"
    required: true
  automatic_release_tag:
    description: "Git tag (for automatic releases)"
    default: "latest"
  delete_exist_tag:
    description: "Should exist Tag delete or not"
    required: false
    default: true
  draft:
    description: "Should this release be marked as a draft?"
    required: false
    default: false
  prerelease:
    description: "Should this release be marked as a pre-release?"
    required: false
    default: true
  title:
    description: "Release title (for automatic releases)"
    required: false
  files:
    description: "Assets to upload to the release"
    required: false
  no_release_page:
    description: "Don't push an Release Page"
    required: false
    default: false
  create_release_tag:
    description: "Will Tag Current Commit"
    required: false
    default: true
outputs:
  automatic_releases_tag:
    description: "The release tag this action just processed"
  upload_url:
    description: "The URL for uploading additional assets to the release"
  release_body:
    description: "Generated Release body"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "red"
