---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - id: "yarn-cache"
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: "actions/cache@v3"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: "yarn install --frozen-lockfile"
      - run: "yarn lint"
      - run: "yarn build"

      - uses: ./
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/index.js
            dist/index.js
        id: "automatic_releases"
